name: main

on:
  push:
    branches: [feat-26]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Yarn install with caching
        uses: bahmutov/npm-install@v1.6.0

      - name: Run build
        run: yarn build

      - name: Send Slack notification on failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: 배포에 실패해 슬픈 페페
          SLACK_ICON_EMOJI: ":sadpepe:"
          SLACK_COLOR: "#ffb300"
          SLACK_MESSAGE: "개발 환경 배포에 실패했습니다. \n@클라"
          SLACK_LINK_NAMES: true
